### ISSUE TITLE
setLeadThrough function is not defined!

### ISSUE THREAD

**Issue by bhomaidan1990** [dorianleveque/yumi-rws#1]
Hi,

The function [setLeadThrough](https://github.com/dorianleveque/yumi-rws/blob/master/src/test_abb_librws.cpp#L19) is not defined, can you please provide the definition of this function? thanks in advance.

**Comment by dorianleveque** [comment]
Hi,

I'm very sorry for you, the changes you are requesting have already been sent in a pull request [#127](https://github.com/ros-industrial/abb_librws/pull/127) which is still under discussion. In the meantime, if you want to have this functionality now, the code is already available on this [fork](https://github.com/dorianleveque/abb_librws).

You can retrieve the changes by cloning it. 
```bash
cd ~/catkin_ws/src
git clone https://github.com/dorianleveque/abb_librws
```
After that, run the commands to compile the library and if no error occurs, the installation of the modified abb_librws library is successful.  

Hope this answers the problem.

**Comment by bhomaidan1990** [comment]
Thanks for your rapid reply.
